# Generated by Django 4.1.7 on 2023-03-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_phone_alter_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihadealer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.location'),
        ),
    ]
