# Generated by Django 4.1.7 on 2023-03-14 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_iha_communication_range_alter_iha_cruise_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihadealer',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
