# Generated by Django 4.1.7 on 2023-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_ihadealer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
