# Generated by Django 4.1.7 on 2023-03-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Iha',
            new_name='iha',
        ),
    ]
